## posts 전체 다 가져오기
GET http://localhost:5500/api/posts
Content-Type: application/json

### post 하나만 가져오기
GET http://localhost:5500/api/posts/1
Content-Type: application/json


###  signup
POST http://localhost:5500/api/users/signup
Content-Type: application/json

{
    "email" : "diasm4@gmail.com",
    "nickname" : "diasm3",
    "password" : "123456"
}


###  signin
POST http://localhost:5500/api/users/signin
Content-Type: application/json

{
    "email" : "diasm4@gmail.com",
    "password" : "123456"
}